{% set version = "1.2.0" %}

package:
  name: git-imerge
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/git-imerge/git-imerge-{{ version }}.tar.gz
  sha256: df5818f40164b916eb089a004a47e5b8febae2b4471a827e3aaa4ebec3831a3f

build:
  entry_points:
    - git-imerge = gitimerge:climain
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - bash-completion
    - pkg-config
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - gitimerge
  commands:
    - pip check
    - git-imerge --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mhagger/git-imerge
  summary: Incremental merge for git
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - danielnachun
